spring:
  main:
    banner-mode: false
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    default-schema: fda_db
    validate-on-migrate: true
    locations: classpath:db/migration
apiAddress:
  baseUrl: https://api.fda.gov/drug/drugsfda.json